#
# docker-compose file for deploying JFROG container registry in Docker.
#

version: '3.8'
services:
  jfrog-container-registry:
    image: releases-docker.jfrog.io/jfrog/artifactory-jcr:7.71.3
    container_name: jfrog-container-registry
    environment:
      - TZ="UTC"
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=80
    volumes:
      - ./configs/system.yaml:/opt/jfrog/artifactory/var/etc/system.yaml
      - ./jcr-data:/var/opt/jfrog/artifactory
    restart: always
    user: "0:0"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  nginx-reverse-proxy:
    image: nginx:1.25.3
    container_name: nginx-reverse-proxy
    environment:
      - TZ="UTC"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/certs:/etc/pki/tls/configs-certs
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
